from gym_minigrid.envs.empty import *
from gym_minigrid.envs.doorkey import *
from gym_minigrid.envs.multiroom import *
from gym_minigrid.envs.fetch import *
from gym_minigrid.envs.gotoobject import *
from gym_minigrid.envs.gotodoor import *
from gym_minigrid.envs.putnear import *
from gym_minigrid.envs.lockedroom import *
from gym_minigrid.envs.playground_v0 import *
from gym_minigrid.envs.redbluedoors import *
from gym_minigrid.envs.unsafe import *
from gym_minigrid.envs.unsafeDoor import *
from gym_minigrid.envs.deadend import *
from gym_minigrid.envs.deadendWater import *
from gym_minigrid.envs.bigEnv import *
from gym_minigrid.envs.doorEnv import *
from gym_minigrid.envs.doorWaterEnv import *
from gym_minigrid.envs.safety import *
from gym_minigrid.envs.cleaningEnv import *
from gym_minigrid.envs.miniclean import *
from gym_minigrid.envs.bigcleanEnv import *
from gym_minigrid.envs.wa6_grid6 import *
from gym_minigrid.envs.dnd2_grid6 import *
from gym_minigrid.envs.li_grid6 import *
from gym_minigrid.envs.lighttest import *

from gym_minigrid.envs.dirtwatlight import *
